#!/bin/bash
sudo apt-get update
sudo apt-get install openssh-server
sudo apt-get install ethtool
sudo apt-get install -y build-essential
sudo apt-get install -y libpcap-dev
sudo apt-get install  libpcre3-dev
sudo apt-get install -y libdumbnet-dev
sudo apt-get install zlib1g-dev
sudo apt-get install bison flex
sudo apt-get install meson
sudo apt-get install libmount-dev
sudo apt install python3-pip
sudo apt-get install xsltproc
sudo apt install libtool
sudo apt install libluajit-5.1-dev
sudo apt install cmake
sudo apt install libffi-dev
sudo apt install libelf-dev
sudo apt-get install libssl-dev
sudo apt install pkg-config
sudo apt install automake1.11
sudo apt install libglib2.0-dev
sudo apt install libntirpc-dev



#cd glib-2.59.0/
#meson -Druntime_libdir=/usr -Dselinux=disabled   _build
#ninja -C _build
#sudo ninja install -C _build

cd ./daq-2.0.6/
make clean
libtoolize --force
autoreconf -i -f -I m4
automake

./configure
make
sudo make install




