#!/bin/bash
# Setup Interfaces
sudo ifconfig p1p1 promisc
sudo ifconfig p5p1 promisc
sudo ifconfig p7p1 promisc
sudo ifconfig p3p1 promisc

sudo brctl addbr br00


sudo brctl addif br00 p5p1
sudo brctl addif br00 p1p1
sudo ifconfig br00 up

#sudo brctl addbr br01	


#sudo brctl addif br01 p7p1
#sudo brctl addif br01 p3p1
#sudo ifconfig br01  up


